--- 

- name: Register Facts
  ios_facts:
    gather_subset: all
    provider: "{{ cli }}"

- name: Enable and describe G1/0
  ios_interface:
    provider: "{{ cli }}"
    name: G1/0
    description: trunk port
