---

- name: create VLAN
  ios_vlan:
    provider: "{{ cli }}"
    aggregate:
      - { 'vlan_id': "{{ id_vlan10 }}", 'name': "{{ name_vlan10 }}", state: present }
      - { 'vlan_id': "{{ id_vlan20 }}", 'name': "{{ name_vlan20 }}", state: present }
      - { 'vlan_id': "{{ id_vlan30 }}", 'name': "{{ name_vlan30 }}", state: present }
